name: Update S3 and invalidate CloudFront cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code.
      uses: actions/checkout@v3

    - name: Configure AWS Credentials.
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:      ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.SECRET_KEY }}
        aws-region:             ap-south-1

    - name: Sync files to S3 bucket.
      run: |
        aws s3 sync . s3://cloud-resume-challenge-4927 --exclude "*" \
        --include "index.html" \
        --include "style.css" \
        --include "script.js" \
        --include "RohithGowthamG_Resume.pdf" \
        --include "icons/*" \
        --include "images/*"



    - name: Invalidate CloudFront Distribution.
      run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION }} \
        --paths "/*"
